services:
  postgres_app_hackathon:
    image: postgres:latest
    container_name: postgres_app_hackathon
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_app_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend

  frontend:
    build:
      context: ./apps/frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    env_file: .env
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    depends_on:
      - postgres_app_hackathon
    ports:
      - "${NEXT_PORT}:${NEXT_PORT}"
    networks:
      - backend

  backend:
    build: ./apps/backend
    container_name: backend
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}?sslmode=disable
    volumes:
      - ./apps/backend:/app
    depends_on:
      - postgres_app_hackathon
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
      - "${PRISMA_PORT}:${PRISMA_PORT}"
    networks:
      - backend

volumes:
  postgres_app_data:

networks:
  backend:
    driver: bridge
